<a href="https://colab.research.google.com/github/nandinirathod1767-ship-it/Special-Task/blob/main/special_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np
import pandas as pd

In [50]:
from google.colab import files
uploaded=files.upload()

Saving simplified_coffee.csv to simplified_coffee (1).csv

In [52]:
filepath='/content/simplified_coffee.csv'
df=pd.read_csv(filepath)

In [11]:
df.head()

,name,roaster,roast,loc_country,origin,100g_USD,rating,review_date,review
0,Ethiopia Shakiso Mormora,Revel Coffee,Medium-Light,United States,Ethiopia,4.70,92,November 2017,"Crisply sweet, cocoa-toned. Lemon blossom, roa..."
1,Ethiopia Suke Quto,Roast House,Medium-Light,United States,Ethiopia,4.19,92,November 2017,"Delicate, sweetly spice-toned. Pink peppercorn..."
2,Ethiopia Gedeb Halo Beriti,Big Creek Coffee Roasters,Medium,United States,Ethiopia,4.85,94,November 2017,"Deeply sweet, subtly pungent. Honey, pear, tan..."
3,Ethiopia Kayon Mountain,Red Rooster Coffee Roaster,Light,United States,Ethiopia,5.14,93,November 2017,"Delicate, richly and sweetly tart. Dried hibis..."
4,Ethiopia Gelgelu Natural Organic,Willoughby's Coffee & Tea,Medium-Light,United States,Ethiopia,3.97,93,November 2017,"High-toned, floral. Dried apricot, magnolia, a..."

In [12]:
df.tail()

,name,roaster,roast,loc_country,origin,100g_USD,rating,review_date,review
1241,Finca Patzibir,El Gran Cafe,Medium-Light,Guatemala,Guatemala,4.70,92,November 2022,"Crisply sweet, nut-toned. Almond brittle, pie ..."
1242,Proyecto Aurora,El Gran Cafe,Medium-Light,Guatemala,Guatemala,2.94,93,November 2022,"Chocolaty, floral-framed. Cocoa nib, honeysuck..."
1243,Finca El Potrero,El Gran Cafe,Medium-Light,Guatemala,Guatemala,2.94,93,November 2022,"High-toned, enticingly sweet. Black cherry, na..."
1244,Chacayá Santiago Atitlán,El Gran Cafe,Medium-Light,Guatemala,Guatemala,4.70,93,November 2022,"Vibrantly sweet, subtly nuanced. Apricot, dar..."
1245,Espresso No. 3,El Gran Cafe,Medium-Light,Guatemala,Guatemala,5.88,94,November 2022,"Evaluated as espresso. Multi-layered, complex...."

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1246 entries, 0 to 1245
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         1246 non-null   object
 1   roaster      1246 non-null   object
 2   roast        1234 non-null   object
 3   loc_country  1246 non-null   object
 4   origin       1246 non-null   object
 5   100g_USD     1246 non-null   float64
 6   rating       1246 non-null   int64
 7   review_date  1246 non-null   object
 8   review       1246 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 87.7+ KB

In [21]:
df.dtypes

name            object
roaster         object
roast           object
loc_country     object
origin          object
100g_USD       float64
rating           int64
review_date     object
review          object
dtype: object

In [22]:
df.describe()

          100g_USD       rating
count  1246.000000  1246.000000
mean     10.479125    93.306581
std      13.486674     1.479413
min       0.170000    84.000000
25%       5.260000    93.000000
50%       6.170000    93.000000
75%       9.600000    94.000000
max     132.280000    97.000000

In [24]:
df.shape

(1246, 9)

In [25]:
df.isnull()

,name,roaster,roast,loc_country,origin,100g_USD,rating,review_date,review
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
1241,False,False,False,False,False,False,False,False,False
1242,False,False,False,False,False,False,False,False,False
1243,False,False,False,False,False,False,False,False,False
1244,False,False,False,False,False,False,False,False,False
1245,False,False,False,False,False,False,False,False,False

In [27]:
df.columns

Index(['name', 'roaster', 'roast', 'loc_country', 'origin', '100g_USD',
       'rating', 'review_date', 'review'],
      dtype='object')

In [30]:
df.sum

<bound method DataFrame.sum of                                   name                     roaster  \
0             Ethiopia Shakiso Mormora                Revel Coffee
1                   Ethiopia Suke Quto                 Roast House
2           Ethiopia Gedeb Halo Beriti   Big Creek Coffee Roasters
3              Ethiopia Kayon Mountain  Red Rooster Coffee Roaster
4     Ethiopia Gelgelu Natural Organic   Willoughby's Coffee & Tea
...                                ...                         ...
1241                    Finca Patzibir                El Gran Cafe
1242                   Proyecto Aurora                El Gran Cafe
1243                  Finca El Potrero                El Gran Cafe
1244          Chacayá Santiago Atitlán                El Gran Cafe
1245                    Espresso No. 3                El Gran Cafe

             roast    loc_country     origin  100g_USD  rating    review_date  \
0     Medium-Light  United States   Ethiopia      4.70      92  November 2017
1     Medium-Light  United States   Ethiopia      4.19      92  November 2017
2           Medium  United States   Ethiopia      4.85      94  November 2017
3            Light  United States   Ethiopia      5.14      93  November 2017
4     Medium-Light  United States   Ethiopia      3.97      93  November 2017
...            ...            ...        ...       ...     ...            ...
1241  Medium-Light      Guatemala  Guatemala      4.70      92  November 2022
1242  Medium-Light      Guatemala  Guatemala      2.94      93  November 2022
1243  Medium-Light      Guatemala  Guatemala      2.94      93  November 2022
1244  Medium-Light      Guatemala  Guatemala      4.70      93  November 2022
1245  Medium-Light      Guatemala  Guatemala      5.88      94  November 2022

                                                 review
0     Crisply sweet, cocoa-toned. Lemon blossom, roa...
1     Delicate, sweetly spice-toned. Pink peppercorn...
2     Deeply sweet, subtly pungent. Honey, pear, tan...
3     Delicate, richly and sweetly tart. Dried hibis...
4     High-toned, floral. Dried apricot, magnolia, a...
...                                                 ...
1241  Crisply sweet, nut-toned. Almond brittle, pie ...
1242  Chocolaty, floral-framed. Cocoa nib, honeysuck...
1243  High-toned, enticingly sweet. Black cherry, na...
1244   Vibrantly sweet, subtly nuanced. Apricot, dar...
1245  Evaluated as espresso. Multi-layered, complex....

[1246 rows x 9 columns]>

In [31]:
df.sample()

,name,roaster,roast,loc_country,origin,100g_USD,rating,review_date,review
1136,Burundi Kabarore Commune,Jaunt Coffee Roasters,Medium-Light,United States,Burundi,5.88,92,June 2022,"Delicate, balanced, sweet-toned. Baking chocol..."

In [34]:
df.nunique()

name           1142
roaster         300
roast             5
loc_country      12
origin           27
100g_USD        345
rating           13
review_date      61
review         1246
dtype: int64

In [36]:
df.value_counts()

name                                                       roaster                 roast         loc_country    origin                            100g_USD  rating  review_date    review
“Naturals”                                                 Hala Tree Kona Coffee   Medium-Light  Hawai'i        Hawai'I                           13.23     92      December 2017  Sweet-toned, fruit-forward. Raspberry, cedar, baker’s chocolate, gardenia, molasses in aroma and cup. Bittersweet structure; velvety mouthfeel. The crisp, gently drying finish leads with notes of chocolate-toned berries in the short, and spicy-sweet florals and aromatic wood notes in the long.                        1
100% Kona Bourbon                                          Hala Tree Kona Coffee   Medium-Light  Hawai'i        Hawai'I                           13.23     93      March 2019     Richly sweet-savory, cocoa-toned. Apricot, cocoa nib, maple syrup, jasmine, hint of marjoram in aroma and cup. Sweetly savory in structure with pert acidity; plush, syrupy mouthfeel. Rich, resonant finish that leads with apricot and jasmine in the short, rounding to crisp cocoa nib in the long.                       1
Wolde Hirbe Natural Espresso                               JBC Coffee Roasters     Medium-Light  United States  Ethiopia                          5.41      92      February 2020  Evaluated as espresso. Crisply sweet, floral-toned. Molasses, plumeria, fir, date, orange zest in aroma and small cup. Full, creamy body; deeply sweet floral- and citrus-toned finish. In three parts milk, the molasses notes are amplified, as are plumeria and fir.                                                       1
Umoja Organic Red Bourbon                                  Equiano Coffee          Light         United States  Democratic Republic Of The Congo  5.29      93      November 2020  Balanced, deeply sweet with savory undertones. Caramel, red apple, baking chocolate, grapefruit zest, freesia-like flowers in aroma and cup. Sweetly savory structure with crisp, lively acidity; lightly syrupy mouthfeel. The finish centers around notes of caramel and freesia with a lasting hint of grapefruit zest.    1
Uluwehi Farm Kona SL34 Yeast-Fermentation Washed Peaberry  Paradise Roasters       Medium-Light  United States  Hawai'I                           35.27     94      February 2022  Richly sweet, deeply layered. Lychee, tangerine zest, mesquite, star jasmine, agave syrup in aroma and cup. Sweet-tart structure with vibrantly bright acidity; very full, syrupy mouthfeel. The finish consolidates to notes of agave syrup and mesquite.                                                                    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
5a Poniente                                                El Gran Cafe            Medium        Guatemala      Guatemala                         1.47      88      December 2021  Richly bittersweet. Dark chocolate, hop flowers, fir, almond, raisin in aroma and cup. Bittersweet structure with gentle acidity; very full, syrupy mouthfeel. The crisp, chocolaty finish is supported by smoky aromatic wood notes.                                                                                         1
100% Kona SL-28                                            Hula Daddy Kona Coffee  Medium-Light  Hawai'i        Hawai'I                           33.05     97      November 2017  Spectacularly sweet and hugely aromatic. Meyer lemon marmalade, cedar, pistachio, guava, jasmine in aroma and cup. Crisply sweet/tart and massively juicy in structure; plush, buoyant mouthfeel. The juicy structure and complex aromatics persist in a long, lingering finish.                                              1
100% Kona Bourbon Pointu Laurina                           Hula Daddy Kona Coffee  Medium-Light  Hawai'i        Hawai'I                           27.76     95      November 2021  Richly aromatic, deeply sweet. Dark chocolate, blackberry, honeysuckle, fresh-cut oak, lemon balm in aroma and cup. Sweet-toned structure with lively acidity; delicately satiny mouthfeel. Rich chocolate and fresh blackberry notes dominate in a flavor-saturated finish.                                                  1
                                                                                                                                                                    February 2020  Deeply and sweetly pungent; layered and intricate. Dark chocolate, raspberry, freesia, port wine, a hint of fresh, fragrant tobacco in aroma and cup. Balanced, quietly forceful in its sweet-savory structure; light but exceptionally silky in mouthfeel. All notes ring on in a layered, flavor-saturated finish.          1
                                                                                                                                                  19.82     95      November 2017  Sweet, deep, intense but balanced. Peach, maple syrup, sandalwood, grapefruit zest, almond, magnolia in aroma and cup. Round, resonantly and sweetly bright in structure. Silky and buoyant in mouthfeel. Deep, long, flavor-saturated finish.                                                                                1
Name: count, Length: 1234, dtype: int64

In [37]:
df.count()

name           1246
roaster        1246
roast          1234
loc_country    1246
origin         1246
100g_USD       1246
rating         1246
review_date    1246
review         1246
dtype: int64

In [44]:
df.max

<bound method DataFrame.max of                                   name                     roaster  \
0             Ethiopia Shakiso Mormora                Revel Coffee
1                   Ethiopia Suke Quto                 Roast House
2           Ethiopia Gedeb Halo Beriti   Big Creek Coffee Roasters
3              Ethiopia Kayon Mountain  Red Rooster Coffee Roaster
4     Ethiopia Gelgelu Natural Organic   Willoughby's Coffee & Tea
...                                ...                         ...
1241                    Finca Patzibir                El Gran Cafe
1242                   Proyecto Aurora                El Gran Cafe
1243                  Finca El Potrero                El Gran Cafe
1244          Chacayá Santiago Atitlán                El Gran Cafe
1245                    Espresso No. 3                El Gran Cafe

             roast    loc_country     origin  100g_USD  rating    review_date  \
0     Medium-Light  United States   Ethiopia      4.70      92  November 2017
1     Medium-Light  United States   Ethiopia      4.19      92  November 2017
2           Medium  United States   Ethiopia      4.85      94  November 2017
3            Light  United States   Ethiopia      5.14      93  November 2017
4     Medium-Light  United States   Ethiopia      3.97      93  November 2017
...            ...            ...        ...       ...     ...            ...
1241  Medium-Light      Guatemala  Guatemala      4.70      92  November 2022
1242  Medium-Light      Guatemala  Guatemala      2.94      93  November 2022
1243  Medium-Light      Guatemala  Guatemala      2.94      93  November 2022
1244  Medium-Light      Guatemala  Guatemala      4.70      93  November 2022
1245  Medium-Light      Guatemala  Guatemala      5.88      94  November 2022

                                                 review
0     Crisply sweet, cocoa-toned. Lemon blossom, roa...
1     Delicate, sweetly spice-toned. Pink peppercorn...
2     Deeply sweet, subtly pungent. Honey, pear, tan...
3     Delicate, richly and sweetly tart. Dried hibis...
4     High-toned, floral. Dried apricot, magnolia, a...
...                                                 ...
1241  Crisply sweet, nut-toned. Almond brittle, pie ...
1242  Chocolaty, floral-framed. Cocoa nib, honeysuck...
1243  High-toned, enticingly sweet. Black cherry, na...
1244   Vibrantly sweet, subtly nuanced. Apricot, dar...
1245  Evaluated as espresso. Multi-layered, complex....

[1246 rows x 9 columns]>

In [45]:
df.min

<bound method DataFrame.min of                                   name                     roaster  \
0             Ethiopia Shakiso Mormora                Revel Coffee
1                   Ethiopia Suke Quto                 Roast House
2           Ethiopia Gedeb Halo Beriti   Big Creek Coffee Roasters
3              Ethiopia Kayon Mountain  Red Rooster Coffee Roaster
4     Ethiopia Gelgelu Natural Organic   Willoughby's Coffee & Tea
...                                ...                         ...
1241                    Finca Patzibir                El Gran Cafe
1242                   Proyecto Aurora                El Gran Cafe
1243                  Finca El Potrero                El Gran Cafe
1244          Chacayá Santiago Atitlán                El Gran Cafe
1245                    Espresso No. 3                El Gran Cafe

             roast    loc_country     origin  100g_USD  rating    review_date  \
0     Medium-Light  United States   Ethiopia      4.70      92  November 2017
1     Medium-Light  United States   Ethiopia      4.19      92  November 2017
2           Medium  United States   Ethiopia      4.85      94  November 2017
3            Light  United States   Ethiopia      5.14      93  November 2017
4     Medium-Light  United States   Ethiopia      3.97      93  November 2017
...            ...            ...        ...       ...     ...            ...
1241  Medium-Light      Guatemala  Guatemala      4.70      92  November 2022
1242  Medium-Light      Guatemala  Guatemala      2.94      93  November 2022
1243  Medium-Light      Guatemala  Guatemala      2.94      93  November 2022
1244  Medium-Light      Guatemala  Guatemala      4.70      93  November 2022
1245  Medium-Light      Guatemala  Guatemala      5.88      94  November 2022

                                                 review
0     Crisply sweet, cocoa-toned. Lemon blossom, roa...
1     Delicate, sweetly spice-toned. Pink peppercorn...
2     Deeply sweet, subtly pungent. Honey, pear, tan...
3     Delicate, richly and sweetly tart. Dried hibis...
4     High-toned, floral. Dried apricot, magnolia, a...
...                                                 ...
1241  Crisply sweet, nut-toned. Almond brittle, pie ...
1242  Chocolaty, floral-framed. Cocoa nib, honeysuck...
1243  High-toned, enticingly sweet. Black cherry, na...
1244   Vibrantly sweet, subtly nuanced. Apricot, dar...
1245  Evaluated as espresso. Multi-layered, complex....

[1246 rows x 9 columns]>

In [49]:
df.mean

<bound method DataFrame.mean of                                   name                     roaster  \
0             Ethiopia Shakiso Mormora                Revel Coffee
1                   Ethiopia Suke Quto                 Roast House
2           Ethiopia Gedeb Halo Beriti   Big Creek Coffee Roasters
3              Ethiopia Kayon Mountain  Red Rooster Coffee Roaster
4     Ethiopia Gelgelu Natural Organic   Willoughby's Coffee & Tea
...                                ...                         ...
1241                    Finca Patzibir                El Gran Cafe
1242                   Proyecto Aurora                El Gran Cafe
1243                  Finca El Potrero                El Gran Cafe
1244          Chacayá Santiago Atitlán                El Gran Cafe
1245                    Espresso No. 3                El Gran Cafe

             roast    loc_country     origin  100g_USD  rating    review_date  \
0     Medium-Light  United States   Ethiopia      4.70      92  November 2017
1     Medium-Light  United States   Ethiopia      4.19      92  November 2017
2           Medium  United States   Ethiopia      4.85      94  November 2017
3            Light  United States   Ethiopia      5.14      93  November 2017
4     Medium-Light  United States   Ethiopia      3.97      93  November 2017
...            ...            ...        ...       ...     ...            ...
1241  Medium-Light      Guatemala  Guatemala      4.70      92  November 2022
1242  Medium-Light      Guatemala  Guatemala      2.94      93  November 2022
1243  Medium-Light      Guatemala  Guatemala      2.94      93  November 2022
1244  Medium-Light      Guatemala  Guatemala      4.70      93  November 2022
1245  Medium-Light      Guatemala  Guatemala      5.88      94  November 2022

                                                 review
0     Crisply sweet, cocoa-toned. Lemon blossom, roa...
1     Delicate, sweetly spice-toned. Pink peppercorn...
2     Deeply sweet, subtly pungent. Honey, pear, tan...
3     Delicate, richly and sweetly tart. Dried hibis...
4     High-toned, floral. Dried apricot, magnolia, a...
...                                                 ...
1241  Crisply sweet, nut-toned. Almond brittle, pie ...
1242  Chocolaty, floral-framed. Cocoa nib, honeysuck...
1243  High-toned, enticingly sweet. Black cherry, na...
1244   Vibrantly sweet, subtly nuanced. Apricot, dar...
1245  Evaluated as espresso. Multi-layered, complex....

[1246 rows x 9 columns]>